### ISSUE TITLE
Undefined constant PHP_INT_MIN and function money_lc()

### ISSUE THREAD

**Issue by torsak** [dpodsiadlo/svg-charts#1]
I got 2 errors when running the example code.
> Use of undefined constant PHP_INT_MIN - assumed 'PHP_INT_MIN'

The workaround I did is adding the code `define('PHP_INT_MIN', ~PHP_INT_MAX);`

And another error is below.
> Call to undefined function money_lc()

The workaround I did is simply updating the function name to `number_format` to get it up and running. 

Thanks for sharing the nice tool :)

**Comment by dpodsiadlo** [comment]
Hey, thanks for reporting! Fixed in v1.0.2
