### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by Ghostscypher** [dpodsiadlo/svg-charts#4]
Do you still accept pull request? I'd like to upgrade the current library to support more charts and more options. I find this library particularly good for dompdf and snappy pdf libraries, for those who have issues generating charts using javascript. I believe it will be of tremendous help. @dpodsiadlo @joserick

**Comment by dpodsiadlo** [comment]
Sure, pull requests are welcome.

**Comment by Ghostscypher** [comment]
Thank you for the quick response.
